# Generated by Django 6.0.4 on 2026-04-14 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('payment', 'Payment'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reception', 'Receptionist'), ('upload1', 'Upload Staff 1'), ('upload2', 'Upload Staff 2'), ('submission', 'Submission'), ('tax', 'Tax/VAT'), ('finance', 'Finance')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
