# Generated by Django 6.0.4 on 2026-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_case_status_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
